import type { Instrument } from '@pm/core';

/** Offline fallback catalog for ticker search when the market-data server is not running. */
const mk = (
  exchange: string,
  symbol: string,
  name: string,
  currency: string,
  country: string,
  assetClass: Instrument['assetClass'],
  sector: string,
  yahoo: string,
): Instrument => ({ id: `${exchange}:${symbol}`, symbol, name, exchange, currency, country, assetClass, sector, providerSymbols: { yahoo }, pricing: 'auto' });

export const CATALOG: Instrument[] = [
  // Colombia (BVC)
  mk('XBOG', 'ECOPETROL', 'Ecopetrol S.A.', 'COP', 'CO', 'equity', 'Energía', 'ECOPETROL.CL'),
  mk('XBOG', 'PFBCOLOM', 'Bancolombia Preferencial', 'COP', 'CO', 'equity', 'Financiero', 'PFBCOLOM.CL'),
  mk('XBOG', 'BCOLOMBIA', 'Bancolombia Ordinaria', 'COP', 'CO', 'equity', 'Financiero', 'BCOLOMBIA.CL'),
  mk('XBOG', 'ISA', 'Interconexión Eléctrica S.A.', 'COP', 'CO', 'equity', 'Servicios públicos', 'ISA.CL'),
  mk('XBOG', 'GEB', 'Grupo Energía Bogotá', 'COP', 'CO', 'equity', 'Servicios públicos', 'GEB.CL'),
  mk('XBOG', 'GRUPOSURA', 'Grupo Sura', 'COP', 'CO', 'equity', 'Financiero', 'GRUPOSURA.CL'),
  mk('XBOG', 'PFGRUPSURA', 'Grupo Sura Preferencial', 'COP', 'CO', 'equity', 'Financiero', 'PFGRUPSURA.CL'),
  mk('XBOG', 'NUTRESA', 'Grupo Nutresa', 'COP', 'CO', 'equity', 'Consumo', 'NUTRESA.CL'),
  mk('XBOG', 'CEMARGOS', 'Cementos Argos', 'COP', 'CO', 'equity', 'Materiales', 'CEMARGOS.CL'),
  mk('XBOG', 'GRUPOARGOS', 'Grupo Argos', 'COP', 'CO', 'equity', 'Industrial', 'GRUPOARGOS.CL'),
  mk('XBOG', 'CELSIA', 'Celsia', 'COP', 'CO', 'equity', 'Servicios públicos', 'CELSIA.CL'),
  mk('XBOG', 'PFDAVVNDA', 'Davivienda Preferencial', 'COP', 'CO', 'equity', 'Financiero', 'PFDAVVNDA.CL'),
  mk('XBOG', 'ICOLCAP', 'iShares MSCI COLCAP', 'COP', 'CO', 'etf', 'Diversificado', 'ICOLCAP.CL'),
  // Brasil (B3)
  mk('BVMF', 'PETR4', 'Petrobras PN', 'BRL', 'BR', 'equity', 'Energía', 'PETR4.SA'),
  mk('BVMF', 'VALE3', 'Vale ON', 'BRL', 'BR', 'equity', 'Materiales', 'VALE3.SA'),
  mk('BVMF', 'ITUB4', 'Itaú Unibanco PN', 'BRL', 'BR', 'equity', 'Financiero', 'ITUB4.SA'),
  mk('BVMF', 'BBDC4', 'Bradesco PN', 'BRL', 'BR', 'equity', 'Financiero', 'BBDC4.SA'),
  mk('BVMF', 'BBAS3', 'Banco do Brasil ON', 'BRL', 'BR', 'equity', 'Financiero', 'BBAS3.SA'),
  mk('BVMF', 'WEGE3', 'WEG ON', 'BRL', 'BR', 'equity', 'Industrial', 'WEGE3.SA'),
  mk('BVMF', 'ABEV3', 'Ambev ON', 'BRL', 'BR', 'equity', 'Consumo', 'ABEV3.SA'),
  mk('BVMF', 'TAEE11', 'Taesa Units', 'BRL', 'BR', 'equity', 'Servicios públicos', 'TAEE11.SA'),
  mk('BVMF', 'BOVA11', 'iShares Ibovespa', 'BRL', 'BR', 'etf', 'Diversificado', 'BOVA11.SA'),
  mk('BVMF', 'IVVB11', 'iShares S&P 500 (B3)', 'BRL', 'BR', 'etf', 'Diversificado', 'IVVB11.SA'),
  mk('BVMF', 'HGLG11', 'CSHG Logística FII', 'BRL', 'BR', 'reit', 'Inmobiliario', 'HGLG11.SA'),
  mk('BVMF', 'MXRF11', 'Maxi Renda FII', 'BRL', 'BR', 'reit', 'Inmobiliario', 'MXRF11.SA'),
  // EE.UU.
  mk('XNAS', 'AAPL', 'Apple Inc.', 'USD', 'US', 'equity', 'Tecnología', 'AAPL'),
  mk('XNAS', 'MSFT', 'Microsoft Corp.', 'USD', 'US', 'equity', 'Tecnología', 'MSFT'),
  mk('XNAS', 'NVDA', 'NVIDIA Corp.', 'USD', 'US', 'equity', 'Tecnología', 'NVDA'),
  mk('XNAS', 'AMZN', 'Amazon.com Inc.', 'USD', 'US', 'equity', 'Consumo', 'AMZN'),
  mk('XNAS', 'GOOGL', 'Alphabet Inc. A', 'USD', 'US', 'equity', 'Comunicaciones', 'GOOGL'),
  mk('XNAS', 'META', 'Meta Platforms', 'USD', 'US', 'equity', 'Comunicaciones', 'META'),
  mk('XNYS', 'KO', 'Coca-Cola Co.', 'USD', 'US', 'equity', 'Consumo', 'KO'),
  mk('XNYS', 'JPM', 'JPMorgan Chase', 'USD', 'US', 'equity', 'Financiero', 'JPM'),
  mk('XNYS', 'CIB', 'Bancolombia ADR', 'USD', 'CO', 'equity', 'Financiero', 'CIB'),
  mk('XNYS', 'EC', 'Ecopetrol ADR', 'USD', 'CO', 'equity', 'Energía', 'EC'),
  mk('XNYS', 'PBR', 'Petrobras ADR', 'USD', 'BR', 'equity', 'Energía', 'PBR'),
  mk('ARCX', 'VOO', 'Vanguard S&P 500 ETF', 'USD', 'US', 'etf', 'Diversificado', 'VOO'),
  mk('ARCX', 'SPY', 'SPDR S&P 500 ETF', 'USD', 'US', 'etf', 'Diversificado', 'SPY'),
  mk('ARCX', 'VT', 'Vanguard Total World', 'USD', 'US', 'etf', 'Diversificado', 'VT'),
  mk('XNAS', 'QQQ', 'Invesco QQQ', 'USD', 'US', 'etf', 'Tecnología', 'QQQ'),
  mk('ARCX', 'URTH', 'iShares MSCI World', 'USD', 'US', 'etf', 'Diversificado', 'URTH'),
  mk('ARCX', 'GXG', 'Global X MSCI Colombia', 'USD', 'CO', 'etf', 'Diversificado', 'GXG'),
  mk('ARCX', 'EWZ', 'iShares MSCI Brazil', 'USD', 'BR', 'etf', 'Diversificado', 'EWZ'),
  // Europa
  mk('XMAD', 'SAN', 'Banco Santander', 'EUR', 'ES', 'equity', 'Financiero', 'SAN.MC'),
  mk('XMAD', 'ITX', 'Inditex', 'EUR', 'ES', 'equity', 'Consumo', 'ITX.MC'),
  mk('XMAD', 'IBE', 'Iberdrola', 'EUR', 'ES', 'equity', 'Servicios públicos', 'IBE.MC'),
  mk('XAMS', 'ASML', 'ASML Holding', 'EUR', 'NL', 'equity', 'Tecnología', 'ASML.AS'),
  mk('XETR', 'SAP', 'SAP SE', 'EUR', 'DE', 'equity', 'Tecnología', 'SAP.DE'),
  mk('XPAR', 'MC', 'LVMH', 'EUR', 'FR', 'equity', 'Consumo', 'MC.PA'),
  mk('XETR', 'EUNL', 'iShares Core MSCI World UCITS', 'EUR', 'IE', 'etf', 'Diversificado', 'EUNL.DE'),
  mk('XLON', 'VWRL', 'Vanguard FTSE All-World UCITS', 'GBP', 'GB', 'etf', 'Diversificado', 'VWRL.L'),
];
